# Generated by Django 4.2 on 2023-04-05 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre equipo')),
                ('id_api', models.PositiveIntegerField(verbose_name='ID API')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo Imagen')),
                ('pais', models.CharField(default='Paraguay', max_length=20, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID API')),
                ('nombre_abreviado', models.CharField(max_length=16, verbose_name='Nombre abreviado')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=70, verbose_name='Apellido')),
                ('posicion', models.CharField(choices=[('DEL', 'Delantero'), ('CEN', 'Mediocampista'), ('DEF', 'Defensa'), ('POR', 'Portero')], max_length=10, verbose_name='Posicion')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura')),
                ('foto', models.URLField(blank=True, null=True, verbose_name='Foto URL')),
                ('foto_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto Imagen')),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='fantasy.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('tipo', models.CharField(choices=[('liga', 'Liga'), ('copa', 'Copa')], max_length=50, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre torneo')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('timestamp', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Epoch time')),
                ('timezone', models.CharField(default='UTC', max_length=10, verbose_name='Timezone')),
                ('id_api', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID API')),
                ('goles_local', models.PositiveSmallIntegerField(default=0, verbose_name='Goles equipo local')),
                ('goles_visitane', models.PositiveSmallIntegerField(default=0, verbose_name='Goles equipo visitante')),
                ('ganador_local', models.BooleanField(default=False, verbose_name='Ganador local')),
                ('ganador_visitante', models.BooleanField(default=False, verbose_name='Ganador visitante')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='fantasy.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='fantasy.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='fantasy.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='fantasy.torneo'),
        ),
        migrations.CreateModel(
            name='PuntuacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.SmallIntegerField()),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_usuarios', to='fantasy.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'torneo')},
            },
        ),
        migrations.CreateModel(
            name='PuntuacionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.SmallIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='fantasy.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_jugadores', to='fantasy.torneo')),
            ],
            options={
                'unique_together': {('jugador', 'torneo')},
            },
        ),
    ]
