# Generated by Django 4.2 on 2023-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='precio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
