# Generated by Django 4.2 on 2023-04-12 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy', '0002_jugador_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('privado', models.BooleanField()),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('codigo', models.SlugField(blank=True, unique=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('DEL', 'Delantero'), ('MED', 'Mediocampista'), ('DEF', 'Defensa'), ('POR', 'Portero')], max_length=10, verbose_name='Posicion'),
        ),
        migrations.AlterField(
            model_name='puntuacionjugador',
            name='puntos',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puntuacionusuario',
            name='puntos',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LigaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.SmallIntegerField(default=0)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.liga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='liga',
            name='usuarios',
            field=models.ManyToManyField(related_name='ligas', through='fantasy.LigaUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AlineacionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitan', models.BooleanField(default=False)),
                ('alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.alineacion')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='alineacion',
            name='jugadores',
            field=models.ManyToManyField(related_name='alineaciones', through='fantasy.AlineacionJugador', to='fantasy.jugador'),
        ),
        migrations.AddField(
            model_name='alineacion',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='fantasy.partido'),
        ),
        migrations.AddField(
            model_name='alineacion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='fantasy.torneo'),
        ),
        migrations.AddField(
            model_name='alineacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EquipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_total', models.SmallIntegerField(default=0)),
                ('jugadores', models.ManyToManyField(related_name='equipos', to='fantasy.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_usuarios', to='fantasy.torneo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'torneo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='alineacion',
            unique_together={('usuario', 'partido')},
        ),
    ]
