# Generated by Django 4.2 on 2023-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_alineacion_liga_alter_jugador_posicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipousuario',
            name='nombre_equipo',
            field=models.CharField(blank=True, default=True, max_length=100, verbose_name='Nombre de equipo'),
        ),
    ]
