# Generated by Django 4.2 on 2023-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_equipousuario_nombre_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='lesionado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Lesionado'),
        ),
    ]
