# Generated by Django 4.2 on 2023-04-16 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy', '0005_jugador_lesionado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ligausuario',
            unique_together={('usuario', 'liga')},
        ),
    ]
