# Generated by Django 4.2 on 2023-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_alter_ligausuario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nombre_abreviado',
            field=models.CharField(max_length=25, verbose_name='Nombre abreviado'),
        ),
    ]
